# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-08 15:06
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160108_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
