# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-08 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160108_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='age_range_max',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='age_range_min',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
